name: Generate

on:
  push:
    branches:
      - actions-generate-info
  schedule: 
    - cron: '00 0 1,15 * *' 
    # runs every hour
    # minute(0-59) / hour(0-23) / day of month(1-31) / month(1-12) / day of week(0-6)
  workflow_dispatch:

jobs:
  data:
    name: Variants
    runs-on: windows-2022
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download latest continuous
        run: gh release download -R endless-sky/endless-sky continuous -p EndlessSky-win64-continuous.zip
      - name: Extract and prepare continuous
        run: |
          Expand-Archive EndlessSky-win64-continuous.zip -DestinationPath endless-sky -Force
          ls
      - uses: actions/checkout@v5
        with:
          ref: 'actions-generate-info'
          path: Omnis
      - name: Install Python libraries
        run: |
          ls
          python3 -m pip install Pillow
          python3 -m pip install numpy
      - name: Generate variants list
        run: |
          ls
          python3 'D:\a\-Omnis\-Omnis\Omnis\.github\workflows\human-variants.py'
      - name: Commit file
        run: |
          git config user.name "script" 
          git config user.email "<>"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated variant list"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
